project:
  type: website
  output-dir: docs

website:
  title: "9890 ML Prediction Competition"
  description: "Website for 9890's Prediction Competition as well as Research Reports throughout the semester."
  site-url: "https://github.com/SethKauf/STA9890-Prediction-Competition/"
  navbar:
    background: primary
    search: false
    left:
      - text: "9890 Final Project"
        href: index.qmd
    right:
      - text: "Research Reports"
        menu: 
          - text: "Bias and Variance Tradeoff and BLUE (Report 1)"
            href: Research_Report_1.qmd
          - text: "Ensemble Learning Techniques for Fair Classification (Report 2)"
            href: Research_Report_2.qmd
format:
  html:
    theme: lux
    toc: false
    self-contained: true